test:
  - tests/**/*
documentation:
  - docs/**/*
  - "**/*.md"
dependencies:
  - package-lock.json
  - yarn.lockfile
ci:
  - .github/workflows/*
  - .travis.yml
github:
  - .github/**/*
git:
  - .gitignore
npm:
  - .npmignore
  - package.json
  - package-lock.json
deployment:
  - netlify.toml
  - _redirects
rollup:
  - rollup.config.mjs
vscode:
  - .vscode/*
labels:
  - .github/pr_labeler.yml
openapi:
  - openapi/*
styling:
  - "**/*.css"
lint:
  - .stylelintrc.json
